#!/usr/bin/env bash
# A Bash script to install certbot and configure HAproxy to accept encrypted traffic for subdomains

# Update package lists
sudo apt-get update

# Install HAProxy
sudo apt-get install haproxy

# Install Certbot
sudo apt-get install certbot

# Obtain SSL certificate
sudo certbot certonly --standalone -d peaceg.tech -d www.peaceg.tech

# HAProxy configuration
configure_haproxy='
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

    # Default SSL material locations
    ca-base /etc/ssl/certs
    crt-base /etc/ssl/private

    # See: https://ssl-config.mozilla.org/#server=haproxy&server-version=2.0.3&config=intermediate
    ssl-default-bind-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
    ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
    ssl-default-bind-options ssl-min-ver TLSv1.2 no-tls-tickets

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend haproxy_balancer
    bind *:80
    mode http
    default_backend web-servers

frontend https
    bind *:443 ssl crt /etc/letsencrypt/live/www.peaceg.tech/fullchain.pem
    http-request add-header X-Forwarded-Proto https

    # Add HSTS header here if uncommented in global section
    # http-response set-header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"

    default_backend web-backend

backend web-servers
    balance roundrobin
    option forwardfor
    server 422693-web-01 54.152.172.214:80 check ssl verify none
    server 422693-web-02 54.175.148.101:80 check ssl verify none

backend web-backend
    balance roundrobin
    server 422693-web-01 54.152.172.214:80 check
    server 422693-web-02 54.175.148.101:80 check
'

# Save HAProxy configuration
echo "$configure_haproxy" > /etc/haproxy/haproxy.cfg > /dev/null

# Restart HAProxy
sudo service haproxy restart
