#!/usr/bin/env bash
# A bash script that transfers a file from client to a server

# Check if the correct number of parameters is provided
if [ "$#" -lt 4 ];
then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
path_to_file=$1
server_ip=$2
username=$3
ssh_key=$4

# Disable strict host key checking for scp and transfer the file using scp
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$path_to_file" "$username"@"$server_ip":~/
exit 0
