#!/usr/bin/env bash

# Update and upgrade system packages
sudo apt-get update -y && sudo apt-get upgrade -y

# Install Nginx
sudo apt-get install -y nginx

# Set ownership for web directories
sudo chown -R "$USER":"$USER" /var/www/
sudo chown -R "$USER":"$USER" /etc/nginx

# Create a simple index page
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html

# Add custom error page configuration to Nginx default site configuration
line="\\
    error_page 404 /404.html;\n\
    location = /404.html {\n\
        root /usr/share/nginx/html;\n\
        internal;\n\
    }"

sudo sed -i "s|# server_name _;|${line}|" /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart

