#!/usr/bin/env bash
#A bash script to display "To infinity and beyond" with 2 seconds pause
#Displaying "I am invincible!!!" in between each iteration
while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
