#!/usr/bin/env bash
# A Bash script that displays Best School 10 times using the while loop

i=1

while ((i <= 20))
do
	case $i in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
		*)
			echo $i
			;;
	esac

	((i++))
done
