#!/usr/bin/env bash
# A Bash script that displays Best School 10 times using the while loop

i=1

while ((i <= 20))
do
	case $i in
		5)
			echo "bad luck from China"
			;;
		10)
			echo "bad luck from Japan"
			;;
		18)
			echo "bad luck from Italy"
			;;
	esac
		echo $i

	((i++))
done
