#!/usr/bin/env bash

sudo apt update
sudo apt install ufw

# Configure ufw to block all incoming traffic by default
sudo ufw default deny incoming

# Allow outgoing traffic
sudo ufw default allow outgoing

# Allow incoming traffic on specific ports
sudo ufw allow 22/tcp   # SSH
sudo ufw allow 80/tcp   # HTTP
sudo ufw allow 443/tcp  # HTTPS SSL

# Enable ufw
sudo ufw enable
