#!/usr/bin/env bash
# Configures an Ubuntu server as follows:
# - 127.0.0.2 resolves to localhost
# - 8.8.8.8 resolves to facebook.com

cp /etc/hosts ~/new_hosts
echo "127.0.0.2 localhost" > ~/new_hosts
echo "8.8.8.8 facebook.com" >> ~/new_hosts
cp ~/new_hosts /etc/hosts

