#!/usr/bin/env bash
# Fixing server
pkill apache2
chmod 644 /etc/nginx/nginx.conf
sudo chown nginx:nginx /etc/nginx/ -R
su - nginx -c "sed -i -e 's/80/8080/g' /etc/nginx/sites-available/default"
su - nginx -c "service nginx restart" 2&> /dev/null
