#!/usr/bin/env bash
# A Bash script that uses ssh to connect to your server using the private key ~/.ssh/school with the user ubuntu

#Set the server address
server_address="54.152.172.214"

#Set the private key path
private_key="~/.ssh/school"

#Set the username
username="ubuntu"

#SSH connection using single-character-flag
ssh -i "$private_key" "$username@$server_address"
